name: medileft
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  sembast: ^3.3.0
  sqflite: ^2.2.8
  crypto: ^3.0.1
  path_provider: ^2.0.11
  # Other dependencies
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  image_picker: ^1.1.2
  provider: ^6.1.4
  geolocator: ^14.0.0
  google_maps_flutter: ^2.12.1
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true